site_name: MaestroNG Documentation
site_description: An orchestrator of Docker-based, multi-hosts environments
site_url: http://maestro-ng.readthedocs.org
repo_url: https://github.com/signalfuse/maestro-ng
theme: readthedocs
pages:
- Home: index.md
- Usage: usage.md
- Guest functions: guest-functions.md
- ChangeLog: changes.md
